### PR TITLE
fix(#90): fix wrong calculation of chain work

### PR DESCRIPTION
**Pull request by dorzepowski**

### CODE REVIEW

**Review by wregulski — DISMISSED** [review]

**Review by sirdeggen — DISMISSED** [review]
chainWork looks correct, thanks.
`work` still showing up as 0, `difficultyTarget` also showing up as 0.

**Comment by sirdeggen** [comment]
Approved the merge above because it seems fixed up to a certain height.

[000000000ea6be82e57bd76b1dfaccd5de0ef63d9a0980310a5148bc4bdb6753](http://localhost:8080/api/v1/chain/header/state/000000000ea6be82e57bd76b1dfaccd5de0ef63d9a0980310a5148bc4bdb6753)

Is correct:
```json
{
"header": {
"hash": "000000000ea6be82e57bd76b1dfaccd5de0ef63d9a0980310a5148bc4bdb6753",
"version": 1,
"prevBlockHash": "000000000b554c46f8eb7264d7d5e334382c6fc3098dabf734de37962ccd7495",
"merkleRoot": "4cfa3f7fe839480c6d5d0301844571038ea02b8a2af27e9fba0809d90d4211f1",
"creationTimestamp": 1276050432,
"difficultyTarget": 0,
"nonce": 70742228,
"work": 71379488893
},
"state": "LONGEST_CHAIN",
"chainWork": 864143750981786,
"height": 60001,
"confirmations": 728007
}
```

**Comment by sirdeggen** [comment]
The break is at 0000000000000002513542a461de351a5a94f96b4bcd3e324a48d2d71b403fe0 (last one which is correct) at height: 282239

**Comment by sirdeggen** [comment]
0000000000000000ef9ee7529607286669763763e0c46acfdefd8a2306de5ca8 or height  282240 is then showing:

```json
{
"header": {
"hash": "0000000000000000ef9ee7529607286669763763e0c46acfdefd8a2306de5ca8",
"version": 2,
"prevBlockHash": "0000000000000002513542a461de351a5a94f96b4bcd3e324a48d2d71b403fe0",
"merkleRoot": "4997281f59f6d37a35f9b743709493cbbc30b2b8a6c027b5f5432e3822dfb23e",
"creationTimestamp": 1390570126,
"difficultyTarget": 0,
"nonce": 895994530,
"work": 0
},
"state": "LONGEST_CHAIN",
"chainWork": 75774420472170361798173,
"height": 282240,
"confirmations": 505768
}
```

**Comment by sirdeggen** [comment]
The correct value for that block is 9422648633005683357 - perhaps this goes over some format limit?

**Comment by sirdeggen** [comment]
Might be associated with this: 

```go
// BlockHeader defines a single block header, used in SPV validations.
type BlockHeader struct {
	Chainwork        *big.Int       `json:"-"`
	CumulatedWork    *big.Int       `json:"work"`
}
```

shortened  for  clarity.

**Comment by sirdeggen** [comment]
Problem is demonstrated here: 
https://go.dev/play/p/cPU5PtD1hL1

Code needs to change here:  https://github.com/libsv/pulse/blob/e74835be99be3c5fec8238cec1035de58578063d/repository/dto/headers.go#L38

Where there is a chainWork = 0 due to the Uint64 parse error. Must be overflowing once the difficulty is high enough.

@dorzepowski see fix above.

**Review by wregulski — APPROVED** [review]

**Review by sirdeggen — APPROVED** [review]

**Pull request merged**
